server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notifications
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: localhost
    port: 1025
    username: yassir
    password: merfouk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

order-confirmation:
  queue: order-confirmations
  exchange: order-confirmations-exchange
  routing-key: order-confirmations-key

payment-confirmation:
  queue: payment-confirmations
  exchange: payment-confirmations-exchange
  routing-key: payment-confirmations-key