server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

order-confirmation:
  queue: order-confirmations
  exchange: order-confirmations-exchange
  routing-key: order-confirmations-key