server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

payment-confirmation:
  queue: payment-confirmations
  exchange: payment-confirmations-exchange
  routing-key: payment-confirmations-key